export type Category = "all" | "laptops" | "keyboards" | "monitors" | "cables" | "storage" | "accessories";

export interface AccessoryItem {
  id: string;
  name: string;
  category: Exclude<Category, "all">;
  image: string;
}

export const categoryLabels: Record<Category, string> = {
  all: "All Items",
  laptops: "Laptops & Printers",
  keyboards: "Keyboards & Mice",
  monitors: "Monitors",
  cables: "Cables & Adapters",
  storage: "Storage",
  accessories: "Other Accessories",
};

export const accessories: AccessoryItem[] = [
  // Laptops & Printers
  { id: "item-1", name: "HP EliteBook 840 G4", category: "laptops", image: "/accessories/images/laptops/elitebook.jpg" },
  { id: "item-2", name: "HP EliteBook 840 G5", category: "laptops", image: "/accessories/images/laptops/elitebook2.jpg" },
  { id: "item-4", name: "HP EliteBook 840 G5", category: "laptops", image: "/accessories/images/laptops/elitebook3.jpg.webp" },
  { id: "item-5", name: '14" Laptop', category: "laptops", image: "/accessories/images/laptops/laptop.jpg" },
  { id: "item-5b", name: "Laptop (variant)", category: "laptops", image: "/accessories/images/laptops/laptop2.jpg" },
  { id: "item-5c", name: "Laptop (variant 2)", category: "laptops", image: "/accessories/images/laptops/laptop3.jpg" },
  { id: "item-3p", name: "Canon Pixma Printer", category: "laptops", image: "/accessories/images/laptops/printer.jpg" },
  { id: "item-6", name: "Canon Pixma G3410 (Black)", category: "laptops", image: "/accessories/images/laptops/printer2.jpg" },

  // Keyboards & Mice
  { id: "item-7", name: "Mechanical Keyboard", category: "keyboards", image: "/accessories/images/keyboards/keyboard.png" },
  { id: "item-8", name: "Wireless Keyboard", category: "keyboards", image: "/accessories/images/keyboards/keyboard2.png" },
  { id: "item-9", name: "Compact Keyboard", category: "keyboards", image: "/accessories/images/keyboards/keyboard3.png" },
  { id: "item-10", name: "Gaming Keyboard (RGB)", category: "keyboards", image: "/accessories/images/keyboards/keyboard4.png" },
  { id: "item-11", name: "Bluetooth Keyboard", category: "keyboards", image: "/accessories/images/keyboards/keyboard5.png" },
  { id: "item-12", name: "Wireless Mouse", category: "keyboards", image: "/accessories/images/keyboards/mouse.jpeg" },
  { id: "item-13", name: "Optical Mouse", category: "keyboards", image: "/accessories/images/keyboards/mouse2.jpg" },
  { id: "item-14", name: "Optical Mouse", category: "keyboards", image: "/accessories/images/keyboards/mouse3.jpg" },
  { id: "item-15", name: "Ergonomic Mouse", category: "keyboards", image: "/accessories/images/keyboards/mouse4.jpeg" },

  // Monitors
  { id: "item-16", name: "LED Monitor", category: "monitors", image: "/accessories/images/monitors/monitor.jpeg" },
  { id: "item-17", name: "Full HD Monitor", category: "monitors", image: "/accessories/images/monitors/monitor2.jpg" },
  { id: "item-18", name: "Wide-screen Monitor", category: "monitors", image: "/accessories/images/monitors/monitor3.png" },

  // Cables & Adapters
  { id: "item-19", name: "USB-C Adapter", category: "cables", image: "/accessories/images/cables/adapter.png" },
  { id: "item-20", name: "Micro-USB to USB-A Adapter", category: "cables", image: "/accessories/images/cables/adapter2.png" },
  { id: "item-21", name: "USB-C Hub 7-Port", category: "cables", image: "/accessories/images/cables/adapter3.png" },
  { id: "item-22", name: "USB-C Adapter (4-in-1)", category: "cables", image: "/accessories/images/cables/adapter4.png" },
  { id: "item-23", name: "USB-C Hub", category: "cables", image: "/accessories/images/cables/adapter5.png" },
  { id: "item-24", name: "DisplayPort to HDMI Adapter", category: "cables", image: "/accessories/images/cables/adapter6.png" },
  { id: "item-25", name: "USB-A and Type-C Flashdrive", category: "cables", image: "/accessories/images/cables/adapter7.jpg" },
  { id: "item-26", name: "USB-A and Type-C Flashdrive", category: "cables", image: "/accessories/images/cables/adapter8.jpg" },
  { id: "item-27", name: "USB Type-A to Type-B Adapter", category: "cables", image: "/accessories/images/cables/adapter9.png" },
  { id: "item-28", name: "USB-C Adapter (variant)", category: "cables", image: "/accessories/images/cables/adapter10.png" },
  { id: "item-29", name: "Type-C Hub", category: "cables", image: "/accessories/images/cables/adapter11.png" },
  { id: "item-30", name: "HDMI Splitter", category: "cables", image: "/accessories/images/cables/adapter12.png" },
  { id: "item-31", name: "USB-C to Serial Adapter", category: "cables", image: "/accessories/images/cables/adapter13.png" },
  { id: "item-32", name: "USB-C to HDMI Adapter", category: "cables", image: "/accessories/images/cables/adapter14.png" },
  { id: "item-33", name: "USB-C to Card Reader Adapter", category: "cables", image: "/accessories/images/cables/adapter15.png" },
  { id: "item-34", name: "USB-C to Multiport Adapter", category: "cables", image: "/accessories/images/cables/adapter16.png" },
  { id: "item-35", name: "USB-C to Ethernet Adapter", category: "cables", image: "/accessories/images/cables/adapter17.png" },
  { id: "item-36", name: "USB Hub", category: "cables", image: "/accessories/images/cables/adapter18.png" },
  { id: "item-37", name: "USB to Multi-adapter Kit", category: "cables", image: "/accessories/images/cables/adapter19.png" },
  { id: "item-38", name: "USB to Multi-adapter Kit", category: "cables", image: "/accessories/images/cables/adapter20.png" },
  { id: "item-39", name: "Laptop Charger", category: "cables", image: "/accessories/images/cables/charger.jpeg" },
  { id: "item-40", name: "Laptop Charger", category: "cables", image: "/accessories/images/cables/charger2.jpeg" },
  { id: "item-41", name: "Laptop Charger", category: "cables", image: "/accessories/images/cables/charger3.jpeg" },
  { id: "item-42", name: "Laptop Charger", category: "cables", image: "/accessories/images/cables/charger4.jpg" },
  { id: "item-43", name: "HDMI Cable", category: "cables", image: "/accessories/images/cables/hdmi.png" },
  { id: "item-44", name: "HDMI Cable (30m)", category: "cables", image: "/accessories/images/cables/hdmi2.jpg" },
  { id: "item-45", name: "HDMI Cable (Short)", category: "cables", image: "/accessories/images/cables/hdmi3.jpg" },
  { id: "item-46", name: "HDMI Cable (Flat)", category: "cables", image: "/accessories/images/cables/hdmi4.png" },
  { id: "item-47", name: "HDMI Cable (Gold-plated)", category: "cables", image: "/accessories/images/cables/hdmi5.png" },
  { id: "item-48", name: "HDMI Cable (Braided)", category: "cables", image: "/accessories/images/cables/hdmi6.png" },
  { id: "item-49", name: "HDMI Cable (High-Speed)", category: "cables", image: "/accessories/images/cables/hdmi7.png" },
  { id: "item-50", name: "HDTV to AV Video Converter", category: "cables", image: "/accessories/images/cables/hdtv-converter.avif" },
  { id: "item-51", name: "HDMI Cable (Multi-pack)", category: "cables", image: "/accessories/images/cables/hdmi8.png" },
  { id: "item-52", name: "HDMI Joiner", category: "cables", image: "/accessories/images/cables/hdmi-joiner.png" },
  { id: "item-53", name: "HDMI Splitter", category: "cables", image: "/accessories/images/cables/hdmi-splitter.png" },
  { id: "item-54", name: "8-Port Ethernet Switch", category: "cables", image: "/accessories/images/cables/switch.jpg" },
  { id: "item-55", name: "Ethernet Cable (Cat6)", category: "cables", image: "/accessories/images/cables/network-cable.jpg" },
  { id: "item-56", name: "Ethernet Cable (Cat6) 2", category: "cables", image: "/accessories/images/cables/network-cable2.jpg" },
  { id: "item-57", name: "Ethernet Cable (Cat6) 3", category: "cables", image: "/accessories/images/cables/network-cable3.jpg" },
  { id: "item-58", name: "Ethernet Cable (Cat6) 4", category: "cables", image: "/accessories/images/cables/network-cable4.jpg" },
  { id: "item-59", name: "Ethernet Cable (Cat6) 5", category: "cables", image: "/accessories/images/cables/network-cable5.jpg" },
  { id: "item-60", name: "Printer Cable", category: "cables", image: "/accessories/images/cables/printer-cable.webp" },
  { id: "item-61", name: "Printer Cable 2", category: "cables", image: "/accessories/images/cables/printer-cable2.jpg" },
  { id: "item-62", name: "Printer Cable 3", category: "cables", image: "/accessories/images/cables/printer-cable3.jpg" },
  { id: "item-63", name: "Printer Cable 4", category: "cables", image: "/accessories/images/cables/printer-cable4.jpg" },
  { id: "item-64", name: "USB-A to USB-A Cable", category: "cables", image: "/accessories/images/cables/usb-to-usb-cable.webp" },
  { id: "item-65", name: "USB Wi-Fi Adapter", category: "cables", image: "/accessories/images/cables/usb-wifi.png" },
  { id: "item-66", name: "OTG Adapter", category: "cables", image: "/accessories/images/cables/otg.png" },

  // Storage
  { id: "item-70", name: "USB Flash Drive", category: "storage", image: "/accessories/images/storage/flashdrive.png" },
  { id: "item-71", name: "128GB Flash Drive", category: "storage", image: "/accessories/images/storage/flashdrive2.png" },
  { id: "item-72", name: "Smartsync Flash Drive", category: "storage", image: "/accessories/images/storage/flashdrive3.jpg" },
  { id: "item-73", name: "Portable HDD", category: "storage", image: "/accessories/images/storage/hdd.jpg" },
  { id: "item-74", name: "1TB External HDD", category: "storage", image: "/accessories/images/storage/hdd2.jpg" },
  { id: "item-75", name: "Portable External HDD", category: "storage", image: "/accessories/images/storage/hdd3.jpg" },
  { id: "item-76", name: "External HDD (Silver)", category: "storage", image: "/accessories/images/storage/hdd4.png" },
  { id: "item-77", name: "External HDD Enclosure", category: "storage", image: "/accessories/images/storage/hddcase.png" },
  { id: "item-78", name: "HDD Enclosure 2", category: "storage", image: "/accessories/images/storage/hddcase2.png" },
  { id: "item-79", name: "HDD Enclosure 3", category: "storage", image: "/accessories/images/storage/hddcase3.png" },
  { id: "item-80", name: "HDD Enclosure 4", category: "storage", image: "/accessories/images/storage/hddcase4.png" },
  { id: "item-81", name: "HDD Enclosure 5", category: "storage", image: "/accessories/images/storage/hddcase5.png" },
  { id: "item-82", name: "HDD Enclosure 6", category: "storage", image: "/accessories/images/storage/hddcase6.png" },
  { id: "item-83", name: "SD Memory Card", category: "storage", image: "/accessories/images/storage/memory-card.png" },
  { id: "item-84", name: "Micro SD Card", category: "storage", image: "/accessories/images/storage/memory-card2.jpg" },
  { id: "item-84b", name: "Micro SD Card (variant)", category: "storage", image: "/accessories/images/storage/memory-card3.png" },
  { id: "item-85", name: "128GB SD Card", category: "storage", image: "/accessories/images/storage/memory-card4.png" },
  { id: "item-86", name: "8GB DDR4 RAM", category: "storage", image: "/accessories/images/storage/ram.png" },
  { id: "item-87", name: "16GB DDR4 RAM", category: "storage", image: "/accessories/images/storage/ram2.png" },
  { id: "item-88", name: "32GB DDR4 RAM", category: "storage", image: "/accessories/images/storage/ram3.png" },

  // Other Accessories
  { id: "item-89", name: "Amazon Fire TV Stick", category: "accessories", image: "/accessories/images/others/tv-stick.avif" },
  { id: "item-90", name: "Fire TV Stick 10K", category: "accessories", image: "/accessories/images/others/tv-stick.png" },
  { id: "item-91", name: "Smart TV Box", category: "accessories", image: "/accessories/images/others/tv-box.jpg" },
  { id: "item-92", name: "Wireless Microphone", category: "accessories", image: "/accessories/images/others/microphone.jpg" },
  { id: "item-93", name: "Portable Speaker", category: "accessories", image: "/accessories/images/others/speaker.webp" },
  { id: "item-94", name: "Printer Ink", category: "accessories", image: "/accessories/images/others/ink.jpg" },
  { id: "item-95", name: "Laptop Battery", category: "accessories", image: "/accessories/images/others/battery.jpg" },
  { id: "item-96", name: "Adjustable Laptop Stand", category: "accessories", image: "/accessories/images/others/laptop-stand.jpg" },
  { id: "item-97", name: "Heat Sink", category: "accessories", image: "/accessories/images/others/heatsink.webp" },
  { id: "item-98", name: "Wireless Mobile Wifi", category: "accessories", image: "/accessories/images/others/wifi.jpg" },
  { id: "item-99", name: "Google Chromecast", category: "accessories", image: "/accessories/images/others/chromecast.jpg" },
  { id: "item-100", name: "USB GPS", category: "accessories", image: "/accessories/images/others/gps.jpg" },
  { id: "item-101", name: "External DVD Drive", category: "accessories", image: "/accessories/images/others/cddrive.jpg" },
  { id: "item-101b", name: "External DVD Drive", category: "accessories", image: "/accessories/images/others/cddrive2.jpg" },
  { id: "item-102", name: "USB Security Camera", category: "accessories", image: "/accessories/images/others/camera.jpg" },
  { id: "item-103", name: "Wifi Indoor Security Camera", category: "accessories", image: "/accessories/images/others/camera2.jpg" },
  { id: "item-104", name: "Wifi Security Camera", category: "accessories", image: "/accessories/images/others/camera3.jpg" },
  { id: "item-105", name: "Power Bank", category: "accessories", image: "/accessories/images/others/powerbank.webp" },
  { id: "item-106", name: "Computer Lock", category: "accessories", image: "/accessories/images/others/computer-lock.jpg" },
  { id: "item-107", name: "Handboss Cleaning Kit", category: "accessories", image: "/accessories/images/others/cleaner.jpg" },
  { id: "item-108", name: "Gaming Gamepad", category: "accessories", image: "/accessories/images/others/gamepad.jpg" },
];
